Vagrant.configure("2") do |config|
  # Define the base box
  config.vm.box = "ubuntu/jammy64"

  # Configure the VM
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--uartmode1", "file", "NUL"]
  end

  # Configure SSH
  # Remove custom private_key_path to use Vagrant's default key
  # config.ssh.private_key_path = "/home/vagrant/.ssh/private_key"

  # Forward port for SSH access
  config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"

  # Provision the VM using shell scripts
  config.vm.provision "shell", inline: <<-SHELL
    #!/bin/bash
    sudo apt-get update
    sudo apt-get install -y curl
    curl -LJO https://raw.githubusercontent.com/NightSquawk/NightlyOrbit/development/setup.sh
    chmod +x setup.sh
  SHELL

  # Enable SSH agent forwarding
  config.ssh.forward_agent = true
end
